services:
  - type: web
    name: rs-hardware-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "./gradlew build"
    envVars:
      - key: PORT
        value: 8080
